"use strict";
/* Income Building — interactive building + content rendering. All external
   strings are escaped; article HTML is generated by our own build.py. */

const $ = (s) => document.querySelector(s);

function esc(s) {
  return String(s ?? "").replace(/[&<>"']/g, (c) => ({
    "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;",
  }[c]));
}

async function loadJSON(path) {
  try {
    const r = await fetch(path, { cache: "no-store" });
    if (!r.ok) return null;
    return await r.json();
  } catch {
    return null;
  }
}

/* ---------------- agent model (tasks adapt to live data) ---------------- */
function agentDefs(d) {
  const nTopics = d.trends?.topics?.length ?? 0;
  const nQ = d.trends?.questions?.length ?? 0;
  const nArt = d.articles?.count ?? 0;
  const slots = d.affiliates?.slots ?? [];
  const nActive = slots.filter((s) => s.url).length;
  const nBriefs = d.briefs?.briefs?.length ?? 0;
  const nDrafts = d.drafts?.drafts?.length ?? 0;
  const nProd = d.products?.products?.length ?? 0;
  return [
    {
      n: 4, name: "Monetization",
      desc: "Turns attention into revenue — transparently, never faked.",
      agents: [
        {
          id: "M-1", name: "Affiliate Manager", role: "Revenue integrity",
          task: `${slots.length} revenue slots defined, ${nActive} active, ${nProd} product${nProd === 1 ? "" : "s"} listed. Placeholders stay empty until real accounts are connected.`,
          receives: "Live articles and reader traffic from the Publisher floor.",
          sends: "Clearly-labeled affiliate links into articles — only where a real account exists.",
          reasoning: "A fake link earns nothing and destroys trust. Null URLs render as \u201ccoming soon\u201d, never as links.",
        },
        {
          id: "M-2", name: "Product Scout", role: "Digital products",
          task: nQ
            ? `Studying ${nQ} real reader questions for product ideas.`
            : "Waiting on reader questions to spot product ideas.",
          receives: "Question backlog from Scouts and content gaps from Creators.",
          sends: "Product briefs to the owner for approval — nothing is built without a human yes.",
          reasoning: "Products only get proposed where demonstrated reader need exists.",
        },
      ],
    },
    {
      n: 3, name: "Publishing",
      desc: "Ships accurate work to the site, every day.",
      agents: [
        {
          id: "P-1", name: "Editor", role: "Accuracy gate",
          task: "Reviewing drafts for accuracy, clarity, and honest claims.",
          receives: "Drafts from the Creator floor.",
          sends: "Approved articles to the Publisher.",
          reasoning: "Every statistic must be verifiable or it gets cut. Guidance is labeled as guidance.",
        },
        {
          id: "P-2", name: "Publisher", role: "Daily shipping",
          task: `${nArt} guides currently live on the site.`,
          receives: "Approved articles from the Editor.",
          sends: "Live articles to the site you are reading now.",
          reasoning: "The pipeline commits data/articles.json; this page renders exactly that file — no hidden edits.",
        },
      ],
    },
    {
      n: 2, name: "Creation",
      desc: "Writes guides and builds simple tools.",
      agents: [
        {
          id: "C-1", name: "Guide Writer", role: "Evergreen content",
          task: `Maintaining ${nArt} evergreen guides; ${nBriefs} brief${nBriefs === 1 ? "" : "s"} and ${nDrafts} AI draft${nDrafts === 1 ? "" : "s"} in the Creator queue.`,
          receives: "Topic shortlist and question backlog from the Scout floor.",
          sends: "Drafts to the Editor.",
          reasoning: "Only widely-established facts go in. No invented statistics, no hype.",
        },
        {
          id: "C-2", name: "Tool Builder", role: "Interactive tools",
          task: "Maintaining the on-site 50/30/20 budget splitter on this page.",
          receives: "Guide topics that need a hands-on companion.",
          sends: "Working tools embedded in the site.",
          reasoning: "A tool must actually work and teach — otherwise it doesn\u2019t ship.",
        },
      ],
    },
    {
      n: 1, name: "Scouting",
      desc: "Finds what people really search and ask about.",
      agents: [
        {
          id: "S-1", name: "Trend Scout", role: "Topic discovery",
          task: nTopics
            ? `Tracking ${nTopics} live topics from this morning\u2019s scout run.`
            : "Waiting for the first scout run to detect topics.",
          receives: "Public signals: Google News RSS, Hacker News, Google Trends US, and (when reachable) Reddit discussions.",
          sends: "A ranked topic shortlist to the Creator floor.",
          reasoning: "Topics are ranked by real mention frequency. Nothing is invented or guessed.",
        },
        {
          id: "S-2", name: "Question Miner", role: "Reader questions",
          task: nQ
            ? `Collecting real questions people ask — ${nQ} banked today.`
            : "No questions captured yet — the scout records public discussions when reachable.",
          receives: "Raw discussion feed from the Trend Scout\u2019s sources.",
          sends: "A question backlog to Creators and the Product Scout.",
          reasoning: "Unanswered real questions become the next guides. The backlog is quoted, not paraphrased into claims.",
        },
      ],
    },
  ];
}

/* ---------------- building ---------------- */
function renderBuilding(d) {
  const el = $("#building");
  el.innerHTML = "";
  const floors = agentDefs(d);
  floors.forEach((f, fi) => {
    const sec = document.createElement("div");
    sec.className = "floor";
    sec.innerHTML =
      `<div class="floor-head"><div class="floor-badge">F${f.n}</div>` +
      `<div><p class="floor-name">${esc(f.name)}</p><p class="floor-desc">${esc(f.desc)}</p></div></div>` +
      `<div class="agents"></div>`;
    const box = sec.querySelector(".agents");
    f.agents.forEach((a) => {
      const b = document.createElement("button");
      b.className = "agent";
      b.type = "button";
      b.innerHTML = `<span class="dot"></span>${esc(a.id)} &middot; ${esc(a.name)}`;
      b.addEventListener("click", (e) => { e.stopPropagation(); openAgentSheet(a, f); });
      box.appendChild(b);
    });
    sec.addEventListener("click", () => openFloorSheet(f));
    el.appendChild(sec);
    if (fi < floors.length - 1) {
      const shaft = document.createElement("div");
      shaft.className = "shaft";
      shaft.setAttribute("aria-hidden", "true");
      shaft.innerHTML = `<span class="packet"></span><span class="packet"></span>`;
      el.appendChild(shaft);
    }
  });
}

/* ---------------- overlays ---------------- */
function kv(k, v) {
  return `<div class="kv"><h4>${esc(k)}</h4><p>${esc(v)}</p></div>`;
}
function showOverlay(id) {
  $("#" + id).hidden = false;
  $("#backdrop").hidden = false;
}
function hideOverlays() {
  $("#agentSheet").hidden = true;
  $("#reader").hidden = true;
  $("#backdrop").hidden = true;
  document.body.style.overflow = "";
}
function openAgentSheet(a, f) {
  $("#sheetBody").innerHTML =
    `<h2>${esc(a.id)} &middot; ${esc(a.name)}</h2>` +
    `<p class="role">${esc(a.role)} — Floor ${f.n} &middot; ${esc(f.name)}</p>` +
    kv("Current task", a.task) + kv("Receives from", a.receives) +
    kv("Sends to", a.sends) + kv("Reasoning", a.reasoning);
  showOverlay("agentSheet");
}
function openFloorSheet(f) {
  $("#sheetBody").innerHTML =
    `<h2>Floor ${f.n} &middot; ${esc(f.name)}</h2>` +
    `<p class="role">${esc(f.desc)}</p>` +
    f.agents.map((a) =>
      `<div class="kv"><h4>${esc(a.id)} &middot; ${esc(a.name)} — ${esc(a.role)}</h4><p>${esc(a.task)}</p></div>`
    ).join("");
  showOverlay("agentSheet");
}

/* ---------------- trends ---------------- */
function renderTrends(t) {
  const el = $("#trends");
  if (!t) {
    el.innerHTML = `<p class="empty">Waiting for the first pipeline run&hellip;</p>`;
    return;
  }
  let h = `<div class="trend-block"><h3>Top topics</h3><div class="chips">` +
    (t.topics || []).map((x) => `<span class="chip">${esc(x.keyword)} &middot; ${x.mentions}</span>`).join("") +
    `</div><p class="src" style="color:var(--muted);font-size:12px;margin:8px 0 0">Scouted ${esc(new Date(t.fetched_at).toLocaleString())}</p></div>`;

  h += `<div class="trend-block"><h3>Real questions people are asking</h3>`;
  if (t.questions && t.questions.length) {
    h += `<ul class="qlist">` + t.questions.slice(0, 8).map((q) =>
      `<li><a href="${esc(q.url)}" target="_blank" rel="noopener">${esc(q.title)}</a> <span class="src">(${esc(q.source)}, ${q.comments} comments)</span></li>`
    ).join("") + `</ul>`;
  } else {
    h += `<p class="empty">No questions captured in the latest run — the scout records public discussions when reachable.</p>`;
  }
  h += `</div>`;

  h += `<div class="trend-block"><h3>In the news</h3><ul class="newslist">` +
    (t.news || []).slice(0, 8).map((n) =>
      `<li><a href="${esc(n.link)}" target="_blank" rel="noopener">${esc(n.title)}</a><br><span class="src">${esc(n.source)} &middot; ${esc(n.published)}</span></li>`
    ).join("") + `</ul></div>`;

  if (t.hn_stories && t.hn_stories.length) {
    h += `<div class="trend-block"><h3>Discussed on Hacker News</h3><ul class="newslist">` +
      t.hn_stories.slice(0, 6).map((s) =>
        `<li><a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.title)}</a><br><span class="src">Hacker News &middot; ${s.score} points</span></li>`
      ).join("") + `</ul></div>`;
  }

  if (t.trending_searches && t.trending_searches.length) {
    h += `<div class="trend-block"><h3>Trending searches (US)</h3><div class="chips">` +
      t.trending_searches.map((x) => `<span class="chip">${esc(x.term)}</span>`).join("") +
      `</div></div>`;
  }

  if (t.errors && t.errors.length) {
    h += `<p style="color:var(--muted);font-size:12px">Scout notes: ${esc(t.errors.join("; "))}</p>`;
  }
  el.innerHTML = h;
}

/* ---------------- articles ---------------- */
let allArticles = [];
let allSlots = [];

function regexEsc(s) {
  return String(s).replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/* Auto-link product mentions for active affiliate slots only.
   First plain-text occurrence per article; inactive slots (null url) are
   never linked — the mention stays plain text. */
function autolinkMentions(html, slots) {
  let out = html;
  for (const s of slots || []) {
    if (!s.url || !s.mention) continue;
    const re = new RegExp("(>[^<>]*?)(" + regexEsc(s.mention) + ")([^<>]*?<)", "i");
    out = out.replace(
      re,
      '$1<a href="' + esc(s.url) + '" target="_blank" rel="sponsored noopener">$2</a>$3'
    );
  }
  return out;
}
function renderArticles(filter = "all") {
  const el = $("#articles");
  if (!allArticles.length) {
    el.innerHTML = `<p class="empty">Waiting for the first pipeline run&hellip;</p>`;
    return;
  }
  const list = allArticles.filter((a) => filter === "all" || (a.topics || []).includes(filter));
  el.innerHTML = list.map((a) => `
    <button class="card" data-slug="${esc(a.slug)}" type="button">
      <h3>${esc(a.title)}</h3><p>${esc(a.excerpt)}</p>
      <div class="meta"><span>${a.words} words</span><span>Reviewed ${esc(a.reviewed)}</span>${(a.topics || []).map((t) => `<span class="tag">${esc(t)}</span>`).join("")}</div>
    </button>`).join("") || `<p class="empty">No guides under this topic yet.</p>`;
  el.querySelectorAll(".card").forEach((c) =>
    c.addEventListener("click", () => openReader(c.dataset.slug)));
}

function openReader(slug) {
  const a = allArticles.find((x) => x.slug === slug);
  if (!a) return;
  $("#readerBody").innerHTML =
    `<h1>${esc(a.title)}</h1>` +
    `<div class="reader-meta"><span>Reviewed ${esc(a.reviewed)}</span><span>${a.words} words</span>${(a.topics || []).map((t) => `<span class="tag">${esc(t)}</span>`).join("")}</div>` +
    autolinkMentions(a.html, allSlots); /* generated by our own build.py from our own markdown */
  const r = $("#reader");
  r.hidden = false;
  r.scrollTop = 0;
  document.body.style.overflow = "hidden";
}

/* ---------------- affiliates ---------------- */
function renderAffiliates(af) {
  const el = $("#affiliates");
  const slots = af?.slots ?? [];
  if (!slots.length) {
    el.innerHTML = `<p class="empty">Waiting for the first pipeline run&hellip;</p>`;
    return;
  }
  el.innerHTML = slots.map((s) => s.url
    ? `<a class="card" href="${esc(s.url)}" target="_blank" rel="sponsored noopener"><h3>${esc(s.label)}</h3><p>${esc(s.note || "")}</p><div class="meta"><span class="tag">Affiliate link</span></div></a>`
    : `<div class="card soon"><h3>${esc(s.label)}</h3><p>${esc(s.note || "")}</p><div class="meta"><span class="soon-label">Coming soon — needs ${esc(s.id_template || "an affiliate account")}</span></div></div>`
  ).join("");
}

/* ---------------- products ---------------- */
function renderProducts(pr) {
  const el = $("#products");
  const list = pr?.products ?? [];
  if (!list.length) {
    el.innerHTML = `<p class="empty">Waiting for the first pipeline run&hellip;</p>`;
    return;
  }
  el.innerHTML = list.map((p) => `
    <div class="card">
      <h3>${esc(p.name)}</h3><p>${esc(p.blurb)}</p>
      <div class="meta">
        <a class="tag" href="${esc(p.free_url)}" style="text-decoration:none">Free download</a>
        ${p.payment_url
          ? `<a class="tag" href="${esc(p.payment_url)}" target="_blank" rel="noopener">Buy premium${p.price ? " — " + esc(p.price) : ""}</a>`
          : `<span class="soon-label">Premium: ${esc(p.payment_note || "connect a payment link to sell")}</span>`}
      </div>
    </div>`).join("");
}

/* ---------------- creator queue (briefs & drafts) ---------------- */
function renderBriefs(br, dr) {
  const el = $("#briefs");
  const cards = [];
  (dr?.drafts || []).forEach((x) => {
    cards.push(
      `<div class="card"><h3>${esc(x.title)}</h3><p>${esc(x.note || "AI draft")}</p>` +
      `<div class="meta"><span class="tag">AI draft — needs human review</span><span>${(x.sources || []).length} sources</span></div></div>`
    );
  });
  (br?.briefs || []).forEach((b) => {
    const srcs = (b.sources || []).slice(0, 3).map((s) =>
      `<a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.source || "source")}</a>`
    ).join(" · ");
    cards.push(
      `<div class="card"><h3>${esc(b.headline_options?.[0] || "Untitled brief")}</h3><p>${esc(b.angle || "")}</p>` +
      `<div class="meta"><span class="tag">${esc(b.kind === "reader-question" ? "Reader question" : "Trending topic")}</span><span>Brief — awaiting the Creator</span></div>` +
      (srcs ? `<p style="font-size:12px;color:var(--muted)">Sources: ${srcs}</p>` : "") +
      `</div>`
    );
  });
  el.innerHTML = cards.join("") || `<p class="empty">No briefs yet — the scout feeds the Creator queue daily.</p>`;
}

/* ---------------- header pill ---------------- */
function renderPill(d) {
  const pill = $("#dataPill");
  const times = [d.articles?.generated_at, d.trends?.fetched_at].filter(Boolean);
  if (!times.length) {
    pill.textContent = "Waiting for pipeline";
    return;
  }
  const latest = times.sort().pop();
  pill.textContent = "Data live · " + new Date(latest).toLocaleDateString();
  pill.classList.add("live");
}

/* ---------------- simulation lab (fake money, real data) ---------------- */
/* Pure math: real articles + real trending topics in, fake-money projections out.
   Traffic model: monthly visitors split across articles, weighted by whether
   the article's topics match currently-trending scout keywords (trending = 3x).
   The Creator is assumed to keep publishing ~4 guides/month from the brief queue.
   Affiliate: visitors x ctr x conversion x AOV x commission, per article.
   Product: site-wide visitors x planner conversion x planner price. */
const SIM_DEFAULTS = {
  start_monthly_visitors: 500, monthly_growth_pct: 15, ctr_pct: 2.0,
  conversion_pct: 3.0, avg_order_value_usd: 45, commission_pct: 4.0,
  planner_price_usd: 9, planner_conversion_pct: 1.0, months: 12,
};
const SIM_NEW_PER_MONTH = 4;
let simTrends = null;
let simAnim = null;

function trendingKeywords(trends) {
  return (trends?.topics || []).map((t) => String(t.keyword || "").toLowerCase()).filter(Boolean);
}
function articleIsTrending(topics, kwList) {
  return (topics || []).some((tp) => {
    const tl = String(tp).toLowerCase();
    return kwList.some((k) => k.includes(tl) || tl.includes(k));
  });
}
function runSimulation(A, articles, trends) {
  const kw = trendingKeywords(trends);
  const roster = (articles || []).map((a) => ({
    label: a.title, trending: articleIsTrending(a.topics, kw),
  }));
  const months = [];
  const perArticleTotal = new Map();
  let cumulative = 0;
  for (let m = 1; m <= A.months; m++) {
    for (let i = 0; i < SIM_NEW_PER_MONTH; i++) {
      roster.push({ label: "New guides · month " + m + " (4)", trending: true });
    }
    const visitors = A.start_monthly_visitors * Math.pow(1 + A.monthly_growth_pct / 100, m - 1);
    const weights = roster.map((r) => (r.trending ? 3 : 1));
    const wSum = weights.reduce((a, b) => a + b, 0) || 1;
    let aff = 0;
    roster.forEach((r, i) => {
      const v = (visitors * weights[i]) / wSum;
      const rev = v * (A.ctr_pct / 100) * (A.conversion_pct / 100) * A.avg_order_value_usd * (A.commission_pct / 100);
      aff += rev;
      perArticleTotal.set(r.label, (perArticleTotal.get(r.label) || 0) + rev);
    });
    const planner = visitors * (A.planner_conversion_pct / 100) * A.planner_price_usd;
    const total = aff + planner;
    cumulative += total;
    months.push({ month: m, visitors, articles: roster.length, affiliate: aff, planner, total, cumulative });
  }
  return { months, perArticleTotal, total: cumulative };
}
function fmtMoney(v) {
  return "$" + Number(v).toLocaleString(undefined, { maximumFractionDigits: v < 10 ? 2 : 0 });
}
function simAssumptions() {
  const num = (id, fb) => {
    const v = parseFloat($("#" + id).value);
    return Number.isFinite(v) && v >= 0 ? v : fb;
  };
  return {
    start_monthly_visitors: num("aVisitors", SIM_DEFAULTS.start_monthly_visitors),
    monthly_growth_pct: num("aGrowth", SIM_DEFAULTS.monthly_growth_pct),
    ctr_pct: num("aCtr", SIM_DEFAULTS.ctr_pct),
    conversion_pct: num("aConv", SIM_DEFAULTS.conversion_pct),
    avg_order_value_usd: num("aAov", SIM_DEFAULTS.avg_order_value_usd),
    commission_pct: num("aCommission", SIM_DEFAULTS.commission_pct),
    planner_price_usd: num("aPrice", SIM_DEFAULTS.planner_price_usd),
    planner_conversion_pct: num("aPlannerConv", SIM_DEFAULTS.planner_conversion_pct),
    months: Math.max(1, Math.min(36, Math.round(num("aMonths", SIM_DEFAULTS.months)))),
  };
}
function fillSimInputs(A) {
  $("#aVisitors").value = A.start_monthly_visitors;
  $("#aGrowth").value = A.monthly_growth_pct;
  $("#aCtr").value = A.ctr_pct;
  $("#aConv").value = A.conversion_pct;
  $("#aAov").value = A.avg_order_value_usd;
  $("#aCommission").value = A.commission_pct;
  $("#aPrice").value = A.planner_price_usd;
  $("#aPlannerConv").value = A.planner_conversion_pct;
  $("#aMonths").value = A.months;
}
function drawSimChart(months, upto) {
  const cv = $("#simChart");
  const dpr = window.devicePixelRatio || 1;
  const W = cv.clientWidth || 320;
  const H = 220;
  cv.width = W * dpr;
  cv.height = H * dpr;
  const ctx = cv.getContext("2d");
  ctx.scale(dpr, dpr);
  ctx.clearRect(0, 0, W, H);
  const n = months.length;
  const maxV = Math.max(...months.map((m) => m.total), 1);
  const padL = 46, padB = 22, padT = 12;
  const innerH = H - padT - padB;
  const cw = (W - padL - 10) / n;
  const bw = Math.max(4, Math.min(26, cw * 0.62));
  ctx.font = "10px sans-serif";
  for (let g = 0; g <= 4; g++) {
    const y = padT + (innerH * g) / 4;
    ctx.strokeStyle = "rgba(255,255,255,.08)";
    ctx.beginPath(); ctx.moveTo(padL, y); ctx.lineTo(W - 10, y); ctx.stroke();
    ctx.fillStyle = "#9aa7b8";
    ctx.fillText(fmtMoney((maxV * (4 - g)) / 4), 4, y + 3);
  }
  const show = upto == null ? n : Math.min(upto, n);
  for (let i = 0; i < show; i++) {
    const m = months[i];
    const x = padL + cw * i + (cw - bw) / 2;
    const yBase = H - padB;
    const hAff = (innerH * m.affiliate) / maxV;
    const hPl = (innerH * m.planner) / maxV;
    ctx.fillStyle = "#4ade80";
    ctx.fillRect(x, yBase - hAff, bw, Math.max(hAff, hAff > 0 ? 1 : 0));
    ctx.fillStyle = "#fbbf24";
    ctx.fillRect(x, yBase - hAff - hPl, bw, Math.max(hPl, hPl > 0 ? 1 : 0));
    ctx.fillStyle = "#9aa7b8";
    if (n <= 18 || i % 2 === 0) ctx.fillText("M" + m.month, x, H - 8);
  }
  ctx.fillStyle = "#4ade80"; ctx.fillRect(padL, 4, 10, 10);
  ctx.fillStyle = "#9aa7b8"; ctx.fillText("Affiliate", padL + 14, 13);
  ctx.fillStyle = "#fbbf24"; ctx.fillRect(padL + 70, 4, 10, 10);
  ctx.fillStyle = "#9aa7b8"; ctx.fillText("Planner", padL + 84, 13);
}
function renderSimResults(res) {
  const last = res.months[res.months.length - 1];
  const stat = (k, v) => `<div class="sim-stat"><span>${esc(k)}</span><strong>${esc(v)}</strong></div>`;
  $("#simSummary").innerHTML =
    stat("Projected total (fake)", fmtMoney(res.total)) +
    stat("Final-month run rate (fake)", fmtMoney(last.total) + "/mo") +
    stat("Guides by month " + last.month, String(last.articles));
  const rows = [...res.perArticleTotal.entries()]
    .map(([label, rev]) => ({ label, rev }))
    .sort((a, b) => b.rev - a.rev);
  $("#simTable").innerHTML =
    `<thead><tr><th>Article / cohort</th><th style="text-align:right">Projected affiliate (fake)</th></tr></thead><tbody>` +
    rows.map((r) => `<tr><td>${esc(r.label)}</td><td class="num">${fmtMoney(r.rev)}</td></tr>`).join("") +
    `</tbody>`;
}
function runSimNow(animated) {
  clearInterval(simAnim);
  simAnim = null;
  const A = simAssumptions();
  const res = runSimulation(A, allArticles, simTrends);
  renderSimResults(res);
  $("#simResults").hidden = false;
  const n = res.months.length;
  if (animated) {
    let i = 0;
    drawSimChart(res.months, 0);
    simAnim = setInterval(() => {
      i++;
      drawSimChart(res.months, i);
      if (i >= n) { clearInterval(simAnim); simAnim = null; }
    }, 140);
    $("#simResults").scrollIntoView({ behavior: "smooth", block: "start" });
  } else {
    drawSimChart(res.months);
  }
}
function initSim(d) {
  simTrends = d.trends;
  const A = Object.assign({}, SIM_DEFAULTS, d.assumptions || {});
  fillSimInputs(A);
  const nT = d.trends?.topics?.length ?? 0;
  $("#simDataNote").textContent =
    `Real inputs right now: ${allArticles.length} live guides and ${nT} trending topics from the latest scout run.`;
  $("#runSimBtn").addEventListener("click", () => runSimNow(true));
  ["aVisitors", "aGrowth", "aCtr", "aConv", "aAov", "aCommission", "aPrice", "aPlannerConv", "aMonths"]
    .forEach((id) => $("#" + id).addEventListener("change", () => {
      if (!$("#simResults").hidden) runSimNow(false);
    }));
  window.addEventListener("resize", () => {
    if (!$("#simResults").hidden) runSimNow(false);
  });
}

/* ---------------- init ---------------- */
(async function init() {
  const [articles, trends, affiliates, products, briefs, drafts, assumptions] = await Promise.all([
    loadJSON("data/articles.json"),
    loadJSON("data/trends.json"),
    loadJSON("data/affiliates.json"),
    loadJSON("data/products.json"),
    loadJSON("data/briefs.json"),
    loadJSON("data/drafts.json"),
    loadJSON("data/assumptions.json"),
  ]);
  const d = { articles, trends, affiliates, products, briefs, drafts, assumptions };
  allArticles = articles?.articles ?? [];
  allSlots = affiliates?.slots ?? [];

  const topics = [...new Set(allArticles.flatMap((a) => a.topics || []))].sort();
  const sel = $("#topicFilter");
  topics.forEach((t) => {
    const o = document.createElement("option");
    o.value = t;
    o.textContent = t.charAt(0).toUpperCase() + t.slice(1);
    sel.appendChild(o);
  });

  renderPill(d);
  renderBuilding(d);
  renderTrends(trends);
  renderArticles();
  renderAffiliates(affiliates);
  renderProducts(products);
  renderBriefs(briefs, drafts);
  initSim(d);

  /* controls */
  $("#pauseBtn").addEventListener("click", () => {
    const p = document.body.classList.toggle("paused");
    $("#pauseBtn").textContent = p ? "Resume motion" : "Pause motion";
  });
  const speeds = [1, 2, 0.5];
  let si = 0;
  $("#speedBtn").addEventListener("click", () => {
    si = (si + 1) % speeds.length;
    const s = speeds[si];
    document.documentElement.style.setProperty("--flow-dur", 3 / s + "s");
    $("#speedBtn").innerHTML = "Speed: " + s + "&times;";
  });
  sel.addEventListener("change", (e) => renderArticles(e.target.value));

  /* overlays */
  $("#backdrop").addEventListener("click", hideOverlays);
  $("#sheetClose").addEventListener("click", hideOverlays);
  $("#readerClose").addEventListener("click", hideOverlays);
  document.addEventListener("keydown", (e) => { if (e.key === "Escape") hideOverlays(); });

  /* budget calculator */
  $("#payInput").addEventListener("input", (e) => {
    const v = parseFloat(e.target.value);
    const out = $("#calcOut");
    if (!(v > 0)) { out.hidden = true; return; }
    out.hidden = false;
    const f = (n) => "$" + Math.round(n).toLocaleString();
    $("#calcNeeds").textContent = f(v * 0.5);
    $("#calcWants").textContent = f(v * 0.3);
    $("#calcSave").textContent = f(v * 0.2);
  });
})();
