"use strict";
/* Income Building — interactive building + content rendering. All external
   strings are escaped; article HTML is generated by our own build.py. */

const $ = (s) => document.querySelector(s);

function esc(s) {
  return String(s ?? "").replace(/[&<>"']/g, (c) => ({
    "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;",
  }[c]));
}

async function loadJSON(path) {
  try {
    const r = await fetch(path, { cache: "no-store" });
    if (!r.ok) return null;
    return await r.json();
  } catch {
    return null;
  }
}

/* ---------------- agent model (tasks adapt to live data) ---------------- */
function agentDefs(d) {
  const nTopics = d.trends?.topics?.length ?? 0;
  const nQ = d.trends?.questions?.length ?? 0;
  const nArt = d.articles?.count ?? 0;
  const slots = d.affiliates?.slots ?? [];
  const nActive = slots.filter((s) => s.url).length;
  return [
    {
      n: 4, name: "Monetization",
      desc: "Turns attention into revenue — transparently, never faked.",
      agents: [
        {
          id: "M-1", name: "Affiliate Manager", role: "Revenue integrity",
          task: `${slots.length} revenue slots defined, ${nActive} active. Placeholders stay empty until real accounts are connected.`,
          receives: "Live articles and reader traffic from the Publisher floor.",
          sends: "Clearly-labeled affiliate links into articles — only where a real account exists.",
          reasoning: "A fake link earns nothing and destroys trust. Null URLs render as \u201ccoming soon\u201d, never as links.",
        },
        {
          id: "M-2", name: "Product Scout", role: "Digital products",
          task: nQ
            ? `Studying ${nQ} real reader questions for product ideas.`
            : "Waiting on reader questions to spot product ideas.",
          receives: "Question backlog from Scouts and content gaps from Creators.",
          sends: "Product briefs to the owner for approval — nothing is built without a human yes.",
          reasoning: "Products only get proposed where demonstrated reader need exists.",
        },
      ],
    },
    {
      n: 3, name: "Publishing",
      desc: "Ships accurate work to the site, every day.",
      agents: [
        {
          id: "P-1", name: "Editor", role: "Accuracy gate",
          task: "Reviewing drafts for accuracy, clarity, and honest claims.",
          receives: "Drafts from the Creator floor.",
          sends: "Approved articles to the Publisher.",
          reasoning: "Every statistic must be verifiable or it gets cut. Guidance is labeled as guidance.",
        },
        {
          id: "P-2", name: "Publisher", role: "Daily shipping",
          task: `${nArt} guides currently live on the site.`,
          receives: "Approved articles from the Editor.",
          sends: "Live articles to the site you are reading now.",
          reasoning: "The pipeline commits data/articles.json; this page renders exactly that file — no hidden edits.",
        },
      ],
    },
    {
      n: 2, name: "Creation",
      desc: "Writes guides and builds simple tools.",
      agents: [
        {
          id: "C-1", name: "Guide Writer", role: "Evergreen content",
          task: `Maintaining ${nArt} evergreen guides; expanding toward reader questions.`,
          receives: "Topic shortlist and question backlog from the Scout floor.",
          sends: "Drafts to the Editor.",
          reasoning: "Only widely-established facts go in. No invented statistics, no hype.",
        },
        {
          id: "C-2", name: "Tool Builder", role: "Interactive tools",
          task: "Maintaining the on-site 50/30/20 budget splitter on this page.",
          receives: "Guide topics that need a hands-on companion.",
          sends: "Working tools embedded in the site.",
          reasoning: "A tool must actually work and teach — otherwise it doesn\u2019t ship.",
        },
      ],
    },
    {
      n: 1, name: "Scouting",
      desc: "Finds what people really search and ask about.",
      agents: [
        {
          id: "S-1", name: "Trend Scout", role: "Topic discovery",
          task: nTopics
            ? `Tracking ${nTopics} live topics from this morning\u2019s scout run.`
            : "Waiting for the first scout run to detect topics.",
          receives: "Public signals: Google News RSS and (when reachable) Reddit discussions.",
          sends: "A ranked topic shortlist to the Creator floor.",
          reasoning: "Topics are ranked by real mention frequency. Nothing is invented or guessed.",
        },
        {
          id: "S-2", name: "Question Miner", role: "Reader questions",
          task: nQ
            ? `Collecting real questions people ask — ${nQ} banked today.`
            : "No questions captured yet — the scout records public discussions when reachable.",
          receives: "Raw discussion feed from the Trend Scout\u2019s sources.",
          sends: "A question backlog to Creators and the Product Scout.",
          reasoning: "Unanswered real questions become the next guides. The backlog is quoted, not paraphrased into claims.",
        },
      ],
    },
  ];
}

/* ---------------- building ---------------- */
function renderBuilding(d) {
  const el = $("#building");
  el.innerHTML = "";
  const floors = agentDefs(d);
  floors.forEach((f, fi) => {
    const sec = document.createElement("div");
    sec.className = "floor";
    sec.innerHTML =
      `<div class="floor-head"><div class="floor-badge">F${f.n}</div>` +
      `<div><p class="floor-name">${esc(f.name)}</p><p class="floor-desc">${esc(f.desc)}</p></div></div>` +
      `<div class="agents"></div>`;
    const box = sec.querySelector(".agents");
    f.agents.forEach((a) => {
      const b = document.createElement("button");
      b.className = "agent";
      b.type = "button";
      b.innerHTML = `<span class="dot"></span>${esc(a.id)} &middot; ${esc(a.name)}`;
      b.addEventListener("click", (e) => { e.stopPropagation(); openAgentSheet(a, f); });
      box.appendChild(b);
    });
    sec.addEventListener("click", () => openFloorSheet(f));
    el.appendChild(sec);
    if (fi < floors.length - 1) {
      const shaft = document.createElement("div");
      shaft.className = "shaft";
      shaft.setAttribute("aria-hidden", "true");
      shaft.innerHTML = `<span class="packet"></span><span class="packet"></span>`;
      el.appendChild(shaft);
    }
  });
}

/* ---------------- overlays ---------------- */
function kv(k, v) {
  return `<div class="kv"><h4>${esc(k)}</h4><p>${esc(v)}</p></div>`;
}
function showOverlay(id) {
  $("#" + id).hidden = false;
  $("#backdrop").hidden = false;
}
function hideOverlays() {
  $("#agentSheet").hidden = true;
  $("#reader").hidden = true;
  $("#backdrop").hidden = true;
  document.body.style.overflow = "";
}
function openAgentSheet(a, f) {
  $("#sheetBody").innerHTML =
    `<h2>${esc(a.id)} &middot; ${esc(a.name)}</h2>` +
    `<p class="role">${esc(a.role)} — Floor ${f.n} &middot; ${esc(f.name)}</p>` +
    kv("Current task", a.task) + kv("Receives from", a.receives) +
    kv("Sends to", a.sends) + kv("Reasoning", a.reasoning);
  showOverlay("agentSheet");
}
function openFloorSheet(f) {
  $("#sheetBody").innerHTML =
    `<h2>Floor ${f.n} &middot; ${esc(f.name)}</h2>` +
    `<p class="role">${esc(f.desc)}</p>` +
    f.agents.map((a) =>
      `<div class="kv"><h4>${esc(a.id)} &middot; ${esc(a.name)} — ${esc(a.role)}</h4><p>${esc(a.task)}</p></div>`
    ).join("");
  showOverlay("agentSheet");
}

/* ---------------- trends ---------------- */
function renderTrends(t) {
  const el = $("#trends");
  if (!t) {
    el.innerHTML = `<p class="empty">Waiting for the first pipeline run&hellip;</p>`;
    return;
  }
  let h = `<div class="trend-block"><h3>Top topics</h3><div class="chips">` +
    (t.topics || []).map((x) => `<span class="chip">${esc(x.keyword)} &middot; ${x.mentions}</span>`).join("") +
    `</div><p class="src" style="color:var(--muted);font-size:12px;margin:8px 0 0">Scouted ${esc(new Date(t.fetched_at).toLocaleString())}</p></div>`;

  h += `<div class="trend-block"><h3>Real questions people are asking</h3>`;
  if (t.questions && t.questions.length) {
    h += `<ul class="qlist">` + t.questions.slice(0, 8).map((q) =>
      `<li><a href="${esc(q.url)}" target="_blank" rel="noopener">${esc(q.title)}</a> <span class="src">(${esc(q.source)}, ${q.comments} comments)</span></li>`
    ).join("") + `</ul>`;
  } else {
    h += `<p class="empty">No questions captured in the latest run — the scout records public discussions when reachable.</p>`;
  }
  h += `</div>`;

  h += `<div class="trend-block"><h3>In the news</h3><ul class="newslist">` +
    (t.news || []).slice(0, 8).map((n) =>
      `<li><a href="${esc(n.link)}" target="_blank" rel="noopener">${esc(n.title)}</a><br><span class="src">${esc(n.source)} &middot; ${esc(n.published)}</span></li>`
    ).join("") + `</ul></div>`;

  if (t.errors && t.errors.length) {
    h += `<p style="color:var(--muted);font-size:12px">Scout notes: ${esc(t.errors.join("; "))}</p>`;
  }
  el.innerHTML = h;
}

/* ---------------- articles ---------------- */
let allArticles = [];
function renderArticles(filter = "all") {
  const el = $("#articles");
  if (!allArticles.length) {
    el.innerHTML = `<p class="empty">Waiting for the first pipeline run&hellip;</p>`;
    return;
  }
  const list = allArticles.filter((a) => filter === "all" || (a.topics || []).includes(filter));
  el.innerHTML = list.map((a) => `
    <button class="card" data-slug="${esc(a.slug)}" type="button">
      <h3>${esc(a.title)}</h3><p>${esc(a.excerpt)}</p>
      <div class="meta"><span>${a.words} words</span><span>Reviewed ${esc(a.reviewed)}</span>${(a.topics || []).map((t) => `<span class="tag">${esc(t)}</span>`).join("")}</div>
    </button>`).join("") || `<p class="empty">No guides under this topic yet.</p>`;
  el.querySelectorAll(".card").forEach((c) =>
    c.addEventListener("click", () => openReader(c.dataset.slug)));
}

function openReader(slug) {
  const a = allArticles.find((x) => x.slug === slug);
  if (!a) return;
  $("#readerBody").innerHTML =
    `<h1>${esc(a.title)}</h1>` +
    `<div class="reader-meta"><span>Reviewed ${esc(a.reviewed)}</span><span>${a.words} words</span>${(a.topics || []).map((t) => `<span class="tag">${esc(t)}</span>`).join("")}</div>` +
    a.html; /* generated by our own build.py from our own markdown */
  const r = $("#reader");
  r.hidden = false;
  r.scrollTop = 0;
  document.body.style.overflow = "hidden";
}

/* ---------------- affiliates ---------------- */
function renderAffiliates(af) {
  const el = $("#affiliates");
  const slots = af?.slots ?? [];
  if (!slots.length) {
    el.innerHTML = `<p class="empty">Waiting for the first pipeline run&hellip;</p>`;
    return;
  }
  el.innerHTML = slots.map((s) => s.url
    ? `<a class="card" href="${esc(s.url)}" target="_blank" rel="sponsored noopener"><h3>${esc(s.label)}</h3><p>${esc(s.note || "")}</p><div class="meta"><span class="tag">Affiliate link</span></div></a>`
    : `<div class="card soon"><h3>${esc(s.label)}</h3><p>${esc(s.note || "")}</p><div class="meta"><span class="soon-label">Coming soon — connect your affiliate account</span></div></div>`
  ).join("");
}

/* ---------------- header pill ---------------- */
function renderPill(d) {
  const pill = $("#dataPill");
  const times = [d.articles?.generated_at, d.trends?.fetched_at].filter(Boolean);
  if (!times.length) {
    pill.textContent = "Waiting for pipeline";
    return;
  }
  const latest = times.sort().pop();
  pill.textContent = "Data live · " + new Date(latest).toLocaleDateString();
  pill.classList.add("live");
}

/* ---------------- init ---------------- */
(async function init() {
  const [articles, trends, affiliates] = await Promise.all([
    loadJSON("data/articles.json"),
    loadJSON("data/trends.json"),
    loadJSON("data/affiliates.json"),
  ]);
  const d = { articles, trends, affiliates };
  allArticles = articles?.articles ?? [];

  const topics = [...new Set(allArticles.flatMap((a) => a.topics || []))].sort();
  const sel = $("#topicFilter");
  topics.forEach((t) => {
    const o = document.createElement("option");
    o.value = t;
    o.textContent = t.charAt(0).toUpperCase() + t.slice(1);
    sel.appendChild(o);
  });

  renderPill(d);
  renderBuilding(d);
  renderTrends(trends);
  renderArticles();
  renderAffiliates(affiliates);

  /* controls */
  $("#pauseBtn").addEventListener("click", () => {
    const p = document.body.classList.toggle("paused");
    $("#pauseBtn").textContent = p ? "Resume motion" : "Pause motion";
  });
  const speeds = [1, 2, 0.5];
  let si = 0;
  $("#speedBtn").addEventListener("click", () => {
    si = (si + 1) % speeds.length;
    const s = speeds[si];
    document.documentElement.style.setProperty("--flow-dur", 3 / s + "s");
    $("#speedBtn").innerHTML = "Speed: " + s + "&times;";
  });
  sel.addEventListener("change", (e) => renderArticles(e.target.value));

  /* overlays */
  $("#backdrop").addEventListener("click", hideOverlays);
  $("#sheetClose").addEventListener("click", hideOverlays);
  $("#readerClose").addEventListener("click", hideOverlays);
  document.addEventListener("keydown", (e) => { if (e.key === "Escape") hideOverlays(); });

  /* budget calculator */
  $("#payInput").addEventListener("input", (e) => {
    const v = parseFloat(e.target.value);
    const out = $("#calcOut");
    if (!(v > 0)) { out.hidden = true; return; }
    out.hidden = false;
    const f = (n) => "$" + Math.round(n).toLocaleString();
    $("#calcNeeds").textContent = f(v * 0.5);
    $("#calcWants").textContent = f(v * 0.3);
    $("#calcSave").textContent = f(v * 0.2);
  });
})();
